# 导入包

In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

# 读取数据

In [3]:
data_path = "../data/raw/marketing_AB.csv"

df = pd.read_csv(data_path)

df.head()

   user id test group  converted  total ads most ads day  most ads hour
0  1069124         ad      False        130       Monday             20
1  1119715         ad      False         93      Tuesday             22
2  1144181         ad      False         21      Tuesday             18
3  1435133         ad      False        355      Tuesday             10
4  1015700         ad      False        276       Friday             14

# 查看数据基本信息

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 588101 entries, 0 to 588100
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   user id        588101 non-null  int64
 1   test group     588101 non-null  str
 2   converted      588101 non-null  bool
 3   total ads      588101 non-null  int64
 4   most ads day   588101 non-null  str
 5   most ads hour  588101 non-null  int64
dtypes: bool(1), int64(3), str(2)
memory usage: 23.0 MB

# 清洗字段名

In [7]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df.columns

Index(['user_id', 'test_group', 'converted', 'total_ads', 'most_ads_day', 'most_ads_hour'], dtype='str')

# 再次查看前几行

In [8]:
df.head()

   user_id test_group  converted  total_ads most_ads_day  most_ads_hour
0  1069124         ad      False        130       Monday             20
1  1119715         ad      False         93      Tuesday             22
2  1144181         ad      False         21      Tuesday             18
3  1435133         ad      False        355      Tuesday             10
4  1015700         ad      False        276       Friday             14

# 查看数据规模

In [9]:
print("数据行数：", df.shape[0])
print("数据列数：", df.shape[1])

数据行数： 588101
数据列数： 6

# 检查缺失值

In [11]:
df.isnull().sum()

user_id          0
test_group       0
converted        0
total_ads        0
most_ads_day     0
most_ads_hour    0
dtype: int64

# 检查重复用户

In [12]:
duplicate_users = df["user_id"].duplicated().sum()

print("重复 user_id 数量：", duplicate_users)

重复 user_id 数量： 0

# 检查实验组

In [13]:
df["test_group"].value_counts()

test_group
ad     564577
psa     23524
Name: count, dtype: int64

# 先做一个最粗的转化率对比

In [14]:
group_summary = df.groupby("test_group").agg(
    users=("user_id", "count"),
    conversions=("converted", "sum"),
    conversion_rate=("converted", "mean")
).reset_index()

group_summary

  test_group   users  conversions  conversion_rate
0         ad  564577        14423         0.025547
1        psa   23524          420         0.017854